export default {
  GET_TERMS: 'GET_TERMS',
  GET_TERMS_SUCCESS: 'GET_TERMS',
  GET_TERMS_ERROR: 'GET_TERMS_ERROR',
  
  ADD_TERM: 'ADD_TERM',
  ADD_TERM_SUCCESS: 'ADD_TERM_SUCCESS',
  ADD_TERM_ERROR: 'ADD_TERM_ERROR',

  GET_TRANSLATE: 'GET_TRANSLATE',
  GET_TRANSLATE_SUCCESS: 'GET_TRANSLATE_SUCCESS',

  REMOVE_DEFINITION: 'REMOVE_DEFINITION',

  ADD_DEFINITION: 'ADD_DEFINITION',
  ADD_DEFINITION_SUCCESS: 'ADD_DEFINITION_SUCCESS',
  ADD_DEFINITION_ERROR: 'ADD_DEFINITION_ERROR',

  GET_DEFINITIONS: 'GET_DEFINITIONS',
  GET_DEFINITIONS_SUCCESS: 'GET_DEFINITIONS_SUCCESS',
  GET_DEFINITIONS_ERROR: 'GET_DEFINITIONS_ERROR',

  TEMP: ''
}